### ISSUE TITLE
opentelemetry enable ignored in seldon-core-v2-setup chart

### ISSUE THREAD

**Issue by franco-bocci** [SeldonIO/helm-charts#39]
The field `opentelemetry.enable` is being ignored in the `seldon-core-v2-setup` chart.
https://github.com/SeldonIO/helm-charts/blob/master/helm-charts/seldon-core-v2-setup/values.yaml#L74

This causes errors at least in the `dataflow-engine` component like:

> [otel.javaagent 2023-06-23 09:58:28:834 +0000] [OkHttp http://seldon-collector:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: seldon-collector: Name or service not known

**Comment by RafalSkolasinski** [comment]
hi, please raise the issue on seldon core repository https://github.com/SeldonIO/seldon-core/
